using BlogApi.Models;
using BlogApi.Services;
using Microsoft.AspNetCore.Mvc;

namespace BlogApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SetupController : ControllerBase
    {
        readonly BlogContext _context;

        static Author Kriss = new Author
        {
            AuthorId = 112233,
            Name="Kristaps",
            Description="Hi, my name is Kristaps"
        };
        static BlogPost Post = new BlogPost
        {
            BlogPostId=10101,
            Title="Example post",
            Summary="This is an example post",
            Body="This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
            AuthorId=Kriss.AuthorId,
            Author=Kriss,
            Tags =new string[]
            {
                "example",
                "post"
            }
        };

        public SetupController(BlogContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult<string> Get()
        {
            if(!_context.Authors.Any())
            {
                _context.Authors.Add(Kriss);
                _context.BlogPosts.Add(Post);

                _context.SaveChanges();
            }
            if(_context.Authors.Any())
            {
                return $"There's an author there: {_context.Authors.First().Name}";
            }
            return "No author there...";
        }
    }
}
